version: "3"
services:
  docker-and-kubernetes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-and-kubernetes_container
    ports:
      - '8000:8080'
    image: "${DOCKER_USERNAME}/docker-and-kubernetes:${APP_VERSION}"
    volumes:
      - ./:/app
      - /app/node_modules