# After
name: Drop API

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      APP_VERSION: ${{ secrets.APP_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        run: |
          sed -i "s/{{APP_VERSION}}/${{ secrets.APP_VERSION }}/g" docker-compose.production.yml

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.production.yml build
          docker-compose -f docker-compose.production.yml push
