name: Sample App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
        
    - name: Build, tag and push Docker image
      run: |
        docker build -t "${{ secrets.DOCKER_USERNAME }}/test:v1-$(date +%s)" .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag "${{ secrets.DOCKER_USERNAME }}/test:v1-$(date +%s)" "${{ secrets.DOCKER_USERNAME }}/test:v1"
        docker push "${{ secrets.DOCKER_USERNAME }}/test:v1-$(date +%s)"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
